authorName: Jessie
experimentName: cifar10_googlenet_v3
trialConcurrency: 2  #trial并发数
maxExecDuration: 100h # 一次trial所用时间*maxTrialNum
maxTrialNum: 10 #根据search_space.json中的定义，共可以有24种超参组合
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false # true表示使用注释定义搜索空间，searchSpacePath将会无效
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    #如果为'maximize'，表示Tuner会试着最大化指标。如果为'minimize'，表示Tuner的目标是将指标最小化。
    optimize_mode: maximize
trial:
  command: python train_googlenet.py
  codeDir: . # 指定Trial文件的目录
  gpuNum: 1   # 表示一次trial占用2个gpu